name: ChamoParty
authors: [ "SQD Studios" ]
version: '${version}'
website: https://github.com/SQD-Studios/ChamoParty

main: net.chamosmp.chamoparty.paper.ChamoPartyPlugin
loader: net.chamosmp.chamoparty.paper.ChamoPartyLoader
api-version: 1.21.11

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Votifier:
      load: BEFORE
      required: false
      join-classpath: true
    zMenu:
      load: BEFORE
      required: false
      join-classpath: true